name: Deploy Frontend

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Frontend
        run: |
          cd frontend
          pnpm install
          pnpm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            rm -rf /var/www/finping/*
          source: "frontend/dist/*"
          target: "/var/www/finping"
          strip_components: 2
